### ISSUE TITLE
Deployment in eu-central-1 fails: Cloudtrail "The operation requested is not supported in the region."

### ISSUE THREAD

**Issue by bpauwels** [aws-solutions/digital-evidence-archive-on-aws#382]
Deploying this solution to eu-central-1 fails at the "deaTrail" CloudTrail resource

`Resource handler returned message: "Invalid request provided: The operation requested is not supported in the region. (Service: CloudTrail, Status Code: 400, Request ID: redacted)" (RequestToken: redacted, HandlerErrorCode: InvalidRequest)`

**Comment by bpauwels** [comment]
Looks like this is the issue is here

https://github.com/aws-solutions/digital-evidence-archive-on-aws/blob/9ed58d56537f8b581cd50e3fc4ab15e9e0fd55f3/source/dea-backend/src/constructs/dea-audit-trail.ts#L146-L159

So far I could not find any information on differences for the `AWS::CloudTrail::Trail DataResource` attribute between regions, but if I remove this I can deploy the solution.

```typescript
    const partition = deaConfig.partition();
    const region = deaConfig.region();
    if (partition !== 'aws-us-gov' && region !== 'eu-central-1' && !deaConfig.isOneClick()) {
...
```

**Comment by DanielAWood** [comment]
Hi @bpauwels are you deploying this in an isengard account?

**Comment by bpauwels** [comment]
Internal issue.
