### ISSUE TITLE
Support for other regions

### ISSUE THREAD

**Issue by bpauwels** [aws-solutions/digital-evidence-archive-on-aws#383]
While deploying this solution to eu-central-1, I saw a few spots that still need to be adjusted to make the solution work in other regions:

1. obsolete
2. Non US regions don't have FIPS endpoints. Ideally this would be configurable in the config json or derived from the region name. 
https://github.com/aws-solutions/digital-evidence-archive-on-aws/blob/9ed58d56537f8b581cd50e3fc4ab15e9e0fd55f3/source/dea-main/src/dea-main-stack.ts#L92
https://github.com/aws-solutions/digital-evidence-archive-on-aws/blob/9ed58d56537f8b581cd50e3fc4ab15e9e0fd55f3/source/dea-main/src/dea-main-stack.ts#L113
3. Pass the region from the config json to aws4interceptor in the frontend code. If no region is passed, it uses the default aws4 behaviour which is "region will try to be calculated from hostname or host or use 'us-east-1' if not given". In my case with a custom domain it used us-east-1 as default and therefore all requests failed.
https://github.com/aws-solutions/digital-evidence-archive-on-aws/blob/9ed58d56537f8b581cd50e3fc4ab15e9e0fd55f3/source/dea-ui/ui/src/helpers/apiHelper.ts#L72-L75

Let me know if I can help / assist with a PR!

**Comment by DanielAWood** [comment]
Thanks @bpauwels I've got these added to our backlog, will update here.

**Comment by DanielleJOAMZN** [comment]
@bpauwels, this issue has been fixed in version 1.0.1
